### ISSUE TITLE
Problem with multiple diffrent servers

### ISSUE THREAD

**Issue by swvw** [bochove/nl.marcovantklooster.sshclient#1]
Have two Servers Nas 1 on (default port) and Nas 2 on (Diffrent SSH port) once I created them.
it will only send the flow command to the last server created.

So If I start the flow 
should trigger Diskstation 2 > it triggers 1 because that the last one I recreated.

This is the flow I test run.
![Screenshot_20210107-224040](https://user-images.githubusercontent.com/19285411/103948536-33909b00-513a-11eb-8cb1-9b38a7b1e22c.jpg)

I Get the following Error:
![Screenshot_20210107-224001](https://user-images.githubusercontent.com/19285411/103948538-34293180-513a-11eb-8686-236e05cb92db.jpg)

IT should start this one.
![Screenshot_20210107-224357](https://user-images.githubusercontent.com/19285411/103948539-34c1c800-513a-11eb-891a-52fe2222119f.jpg)

But insted it start this one.
![Screenshot_20210107-224347](https://user-images.githubusercontent.com/19285411/103948540-34c1c800-513a-11eb-8c09-752bcfcd7d12.jpg)

**Comment by bochove** [comment]
@swvw Can you confirm this issue is fixed in the latest test version?

**Comment by pjmpessers** [comment]
Strange enough is the other raspberry pi listening to the "sudo shutdown -h now" and is the previous working raspberry pi ignoring this with a red exclamation mark in the flow. By device i get the error:"error: "level":"client-authentication"

**Comment by bochove** [comment]
@pjmpessers I updated some more, when a device reported an error with client-authentication it is disabled. You need to update it's settings so the entered credentials are valid. After updating device settings a device is marked as available again.

**Comment by pjmpessers** [comment]
Thank you. I will try it as soon as possible. When i get home.

**Comment by pjmpessers** [comment]
It works perfect now. Both raspberry pi's receive the command:"sudo shutdown -h now" without interfering each other. 

Happy with it. Thank you very much.

**Comment by swvw** [comment]
Have been trying to install v0.3.5 and adding the two clients.
but keep getting This app has unexpectedly stopped.

![Screenshot_20210122-131510](https://user-images.githubusercontent.com/19285411/105489772-16200d00-5cb4-11eb-9c5e-5286ac17d376.jpg)

**Comment by pjmpessers** [comment]
Have you tried this link instead of sideload?
Also remove and reattach both NAS?

https://homey.app/nl-nl/app/nl.marcovantklooster.sshclient/SSH-Client/test/

**Comment by swvw** [comment]
Yes the link works! thanks!

**Comment by pjmpessers** [comment]
Great to hear. Your welcome.
