### ISSUE TITLE
Problem with ssh when in use with 2 raspberry pi

### ISSUE THREAD

**Issue by pjmpessers** [bochove/nl.marcovantklooster.sshclient#2]
I like this app. It has great potential for shutting down raspberry pi before switching off.

I have one in the living room and bedroom. Both pi's have two separate and different server-names. One called raspberrypi-s and the other raspberry-h. Both have fixed ip addresses. One 192.168.1.100 and the other 192.168.1.101. Both have different passwords. But trying to turn off the raspberry pi in the living room with the ssh-client on homey always turn off the one in the bedroom. Also when i use the ssh-client specifically made for the pi in the bedroom. So both ssh-client that was setup on homey are both shutting down the pi in the bedroom. Even when one is setup with ip, etc for livingroom pi.

Update: The last one added is the one with a red aclamation mark with the code:" error:{errno";"EHOSTUNREACH","EHOSTUNREACH","syscall","connect","address","192.168.1.100","port":22,"level","client-socket"}". This is strange, because this is the raspberrypi that is listening to both added SSH-client on homey when i give the command:"sudo shutdown -h now". Is the last added SSH-client maybe overwriting the first added SSH-client instead of adding a second new one?

**Comment by bochove** [comment]
This is a duplicate of:
https://github.com/bochove/nl.marcovantklooster.sshclient/issues/1

**Comment by pjmpessers** [comment]
Strange enough is the other raspberry pi listening to the "sudo shutdown -h now" and is the previous working raspberry pi ignoring this with a red exclamation mark in the flow. By device i get the error:"error: "level":"client-authentication"
